In [1]:
# Import necessary libraries 
import pandas as pd
import sqlite3
import sqlalchemy as sqla

In [2]:
#Reading in csv created from milestone 2
Milestone2 = pd.read_csv("Milestone2_df.csv", sep=",", header=None, engine='python', encoding="utf-8-sig") # imports the dataset
Milestone2

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
0,index,name,real_name,full_name,overall_score,history_text,powers_text,intelligence_score,strength_score,speed_score,...,has_accelerated_healing,has_weapons_master,has_intelligence,has_reflexes,has_super_speed,has_durability,has_stamina,has_agility,has_super_strength,attribute_score
1,1,3-D Man,"Delroy Garrett, Jr.","Delroy Garrett, Jr.",6,"Delroy Garrett, Jr. grew up to become a track ...",NaN,85,30,60,...,0,0,0,0,1,0,0,0,1,345
2,2,514A (Gotham),Bruce Wayne,NaN,10,He was one of the many prisoners of Indian Hil...,NaN,100,20,30,...,0,0,0,1,0,1,0,0,1,335
3,3,A.I.M. Agent,NaN,NaN,7,A.I.M. agents are both soldiers and scientists...,NaN,90,5,20,...,0,1,0,0,0,0,0,0,0,235
4,4,A.M.A.Z.O. (CW),NaN,NaN,22,The Anti Meta-human Adaptive Zootomic Organism...,"With its metallic body, it easily overpowered ...",90,100,100,...,0,1,0,0,0,0,0,0,0,590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373,1479,Zane,Zane,Zane,25,Zane was created by Dr. Julien in a small work...,"As a Nindroid, Zane has increased stamina and ...",100,35,50,...,0,1,1,1,0,1,1,1,1,445
1374,1480,Zatanna,Zatanna Zatara,Zatanna Zatara,10,Zatanna is the daughter of adventurer John Zat...,Zatanna is genetically talented with her magi...,90,10,25,...,0,0,0,0,0,0,0,0,0,310
1375,1483,Zoom,Hunter Zolomon,Hunter Zolomon,9,Hunter Zolomon had a troubled relationship wi...,"Zoom is able to alter time, to make himself ev...",75,10,100,...,0,0,0,0,1,0,0,0,0,345
1376,1484,Zoom (New 52),Hunter Zolomon,NaN,20,"Hunter Zolomon is better known as Zoom, a spee...",After tricking Barry Allen and Wally West into...,95,50,100,...,1,0,1,1,1,1,1,1,1,500
1377,1485,Zzzax,NaN,NaN,5,Zzzax was the product of an accident that occu...,NaN,45,80,75,...,0,0,0,0,1,0,0,1,1,425

In [3]:
#Reading in csv created from milestone 4
Milestone4 = pd.read_csv("milestone4.csv", sep=",", header=None, engine='python', encoding="utf-8-sig") # imports the dataset
Milestone4

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,index,id,name,slug,intelligence,strength,speed,durability,power,combat,...,hairColor,fullName,alterEgos,aliases,placeOfBirth,firstAppearance,publisher,alignment,occupation,base
1,0,1,A-Bomb,1-a-bomb,38,100,17,80,24,64,...,No Hair,Richard Milhouse Jones,No alter egos found.,['Rick Jones'],"Scarsdale, Arizona","Hulk Vol 2 #2 (April, 2008) (as A-Bomb)",Marvel Comics,good,"Musician, adventurer, author; formerly talk sh...",-
2,1,2,Abe Sapien,2-abe-sapien,88,28,35,65,100,85,...,No Hair,Abraham Sapien,No alter egos found.,"['Langdon Everett Caul', 'Abraham Sapien', 'La...",-,Hellboy: Seed of Destruction (1993),Dark Horse Comics,good,Paranormal Investigator,-
3,2,3,Abin Sur,3-abin-sur,50,90,53,64,99,65,...,No Hair,NaN,No alter egos found.,['Lagzia'],Ungara,"Showcase #22 (October, 1959)",DC Comics,good,"Green Lantern, former history professor",Oa
4,3,4,Abomination,4-abomination,63,80,53,90,62,95,...,No Hair,Emil Blonsky,No alter egos found.,"['Agent R-7', 'Ravager of Worlds']","Zagreb, Yugoslavia",Tales to Astonish #90,Marvel Comics,bad,Ex-Spy,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,558,727,Yellowjacket II,727-yellowjacket-ii,50,10,35,28,31,28,...,Strawberry Blond,Rita DeMara,No alter egos found.,['-'],-,Avengers #264,Marvel Comics,good,"Adventurer; former criminal, electronics engineer",New York City area
560,559,728,Ymir,728-ymir,50,100,27,100,98,28,...,No Hair,Ymir,No alter egos found.,['Aurgelmir'],Niffleheim,JOURNEY INTO MYSTERY #97,Marvel Comics,good,-,Niffleheim
561,560,729,Yoda,729-yoda,88,52,33,25,100,90,...,White,Yoda,No alter egos found.,['-'],-,Star Wars: Episode V - The Empire Strikes Back...,George Lucas,good,-,-
562,561,730,Zatanna,730-zatanna,81,10,23,28,100,56,...,Black,Zatanna Zatara,No alter egos found.,['-'],-,Hawkman #4,DC Comics,good,-,-
563,562,731,Zoom,731-zoom,50,10,100,28,100,28,...,Brown,Hunter Zolomon,No alter egos found.,['-'],-,Flash Secret Files #3,DC Comics,bad,-,"Keystone City, Kansas"

In [4]:
#Reading in csv created from milestone 3, 1 of 2
Milestone3a = pd.read_csv("Milestone3_df2.csv", sep=",", header=None, engine='python', encoding="utf-8-sig") # imports the dataset
Milestone3a

,0,1,2,3,4,5,6
0,index,Rank,Film,Gross[64] ($ millions),Year,name,Source
1,1,1,Avengers: Endgame,"$1,223.60",2019,Avengers,Marvel
2,2,2,Avengers: Infinity War,$640.50,2018,[66],NaN
3,3,3,Captain Marvel,$456.70,2019,Captain Marvel,[67]
4,4,4,Batman v Superman: Dawn of Justice,$422.50,2016,Batman/Superman,DC
5,5,5,The Avengers,$392.50,2012,Avengers,Marvel
6,6,6,Avengers: Age of Ultron,$392.40,2015,[70],NaN
7,7,7,Spider-Man 3,$381.70,2007,Spider-Man,[71]
8,8,8,Captain America: Civil War,$379.50,2016,Captain America,[72]
9,9,9,Iron Man 3,$372.50,2013,Iron Man,[73]
10,10,10,Black Panther,$371.40,2018,Black Panther,[74]
11,11,11,Deadpool 2,$300.40,2018,[75],NaN
12,12,12,Spider-Man: Far From Home,$295.80,2019,Spider-Man,[76]
13,13,13,Justice League,$278.80,2017,Justice League,DC
14,14,14,Suicide Squad,$267.00,2016,Suicide Squad,[78]
15,15,15,Deadpool,$264.70,2016,Marvel,[79]
16,16,16,X-Men: Days of Future Past,$262.90,2014,X-Men,[80]
17,17,17,Spider-Man: Homecoming,$256.50,2017,Spider-Man,[81]
18,18,18,Guardians of the Galaxy Vol. 2,$252.50,2017,[82],NaN
19,19,19,The Dark Knight Rises,$248.90,2012,Batman,DC
20,20,20,Joker,$248.40,2019,Joker,[84]
21,21,21,Logan,$247.40,2017,Wolverine,Marvel
22,22,22,Incredibles 2,$235.80,2018,The Incredibles,Pixar
23,23,23,Thor: Ragnarok,$231.80,2017,Thor,Marvel
24,24,24,Wonder Woman,$228.30,2018,DC,[88]
25,25,25,Iron Man 2,$220.80,2010,Iron Man,Marvel
26,26,26,Venom,$207.40,2018,Venom,[90]
27,27,27,Man of Steel,$202.00,2013,Superman,DC
28,28,28,Iron Man,$201.20,2008,Iron Man,Marvel
29,29,29,Godzilla,$200,2014,Godzilla,Toho
30,30,30,The Dark Knight,$199.70,2008,Batman,DC
31,31,30,Thor: The Dark World,$195.10,2013,Thor,Marvel
32,32,31,Spider-Man 2,$189.40,2004,Spider-Man,[96]
33,33,32,The Amazing Spider-Man,$188.20,2012,[97],NaN
34,34,33,Hancock,$182.50,2008,Hancock,Vincent Ngo
35,35,34,X-Men: The Last Stand,$179.00,2006,X-Men,Marvel
36,36,35,Doctor Strange,$172.80,2016,Doctor Strange,[100]
37,37,36,Captain America: The Winter Soldier,$170.20,2014,Captain America,[101]
38,38,37,Aquaman,$166.80,2018,Aquaman,DC
39,39,38,X-Men: Apocalypse,$166.60,2016,X-Men,Marvel
40,40,39,Ant-Man and the Wasp,$161.70,2018,Ant-Man,[104]
41,41,40,Guardians of the Galaxy,$160.70,2014,Guardians of the Galaxy,[105]
42,42,41,Shazam!,$159.10,2019,Shazam!,DC
43,43,42,X-Men Origins: Wolverine,$158.20,2009,Wolverine,Marvel
44,44,43,X2,$154.80,2003,X-Men,[108]
45,45,44,The Wolverine,$139.60,2013,Wolverine,[109]
46,46,45,The Amazing Spider-Man 2,$137.80,2014,Spider-Man,[110]
47,47,46,Dark Phoenix,$136.60,2019,X-Men,[111]
48,48,47,Spider-Man,$125.90,2002,Spider-Man,[112]
49,49,49,X-Men: First Class,$116.10,2011,X-Men,[113]
50,50,50,Ant-Man,$113.60,2015,Ant-Man,[114]

In [5]:
#Reading in csv created from milestone 3, 2 of 2
Milestone3b = pd.read_csv("Milestone3_df3.csv", sep=",", header=None, engine='python', encoding="utf-8-sig") # imports the dataset
Milestone3b

,0,1,2,3,4,5,6
0,index,Rank,Film,Worldwide gross,Year,name,Source
1,1,1,Avengers: Endgame,"$2,797,800,564",2019,Avengers,Marvel
2,2,2,Avengers: Infinity War,"$2,048,359,754",2018,[2],NaN
3,3,3,The Avengers,"$1,518,812,988",2012,[3],NaN
4,4,4,Avengers: Age of Ultron,"$1,405,403,694",2015,[4],NaN
5,5,5,Black Panther,"$1,346,913,171",2018,Black Panther,[5]
6,6,6,Incredibles 2,"$1,242,805,359",2018,Pixar,[6]
7,7,7,Iron Man 3,"$1,214,811,252",2013,Iron Man,Marvel
8,8,8,Captain America: Civil War,"$1,153,304,495",2016,Captain America,[8]
9,9,9,Aquaman,"$1,148,161,807",2018,Aquaman,DC
10,10,10,Spider-Man: Far From Home,"$1,131,927,996",2019,Spider-Man,Marvel
11,11,11,Captain Marvel,"$1,128,274,794",2019,[11],NaN
12,12,12,The Dark Knight Rises,"$1,081,041,287",2012,Batman,DC
13,13,13,Joker,"$1,074,251,311",2019,Joker,[13]
14,14,14,The Dark Knight,"$1,004,558,444",2008,Batman,[14]
15,15,15,Spider-Man 3,"$890,871,626",2007,Spider-Man,Marvel
16,16,16,Spider-Man: Homecoming,"$880,166,924",2017,[16],NaN
17,17,17,Batman v Superman: Dawn of Justice,"$873,634,919",2016,Batman andSuperman,DC
18,18,18,Guardians of the Galaxy Vol. 2,"$863,756,051",2017,Guardians of the Galaxy,Marvel
19,19,19,Venom,"$856,085,151",2018,Venom,[19]
20,20,20,Thor: Ragnarok,"$853,977,126",2017,Thor,[20]
21,21,21,Wonder Woman,"$821,847,012",2017,Wonder Woman,DC
22,22,22,Spider-Man,"$821,708,551",2002,Spider-Man,Marvel
23,23,23,Spider-Man 2,"$788,976,453",2004,[23],NaN
24,24,24,Deadpool 2,"$785,046,920",2018,Deadpool,[24]
25,25,25,Deadpool,"$783,112,979",2016,[25],NaN
26,26,26,Guardians of the Galaxy,"$773,328,629",2014,Guardians of the Galaxy,[26]
27,27,27,The Amazing Spider-Man,"$757,930,663",2012,Spider-Man,[27]
28,28,28,X-Men: Days of Future Past,"$747,862,775",2014,X-Men,[28]
29,29,29,Suicide Squad,"$746,846,894",2016,Suicide Squad,DC
30,30,30,The Matrix Reloaded,"$739,412,035",2003,Neo,Warner
31,31,31,Captain America: The Winter Soldier,"$714,421,503",2014,Captain America,Marvel
32,32,32,The Amazing Spider-Man 2,"$708,982,323",2014,[33],NaN
33,33,33,Doctor Strange,"$677,718,395",2016,Doctor Strange,[34]
34,34,34,Man of Steel,"$668,045,518",2013,Superman,DC
35,35,35,Justice League,"$657,924,295",2017,Justice League,[36]
36,36,36,Big Hero 6,"$657,818,612",2014,Big Hero 6,Marvel
37,37,37,Thor: The Dark World,"$644,571,402",2013,Thor,[38]
38,38,38,The Incredibles,"$633,019,734",2004,The Incredibles,Pixar
39,39,39,Hancock,"$624,386,746",2008,Hancock,Vincent Ngo
40,40,40,Iron Man 2,"$623,933,331",2010,Iron Man,Marvel
41,41,41,Ant-Man and the Wasp,"$622,674,139",2018,Ant-ManandWasp,[42]
42,42,42,Logan,"$619,021,436",2017,Wolverine,[43]
43,43,43,Iron Man,"$585,174,222",2008,Iron Man,[44]
44,44,44,X-Men: Apocalypse,"$543,934,787",2016,X-Men,[45]
45,45,45,Godzilla,"$529,076,069",2014,Godzilla,Toho
46,46,46,Ant-Man,"$519,311,965",2015,Ant-Man,Marvel
47,47,47,Teenage Mutant Ninja Turtles,"$493,333,584",2014,Teenage Mutant Ninja Turtles,Mirage
48,48,48,The Matrix,"$465,343,787",1999,Neo,Warner
49,49,49,X-Men: The Last Stand,"$459,359,555",2006,X-Men,Marvel
50,50,50,Thor,"$449,326,618",2011,Thor,[53]

In [7]:
#Merging my first two dataframes. Using combine first so df_covid1 is my source of truth
merge = Milestone2.combine_first(Milestone4)
merge

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
0,index,name,real_name,full_name,overall_score,history_text,powers_text,intelligence_score,strength_score,speed_score,...,has_accelerated_healing,has_weapons_master,has_intelligence,has_reflexes,has_super_speed,has_durability,has_stamina,has_agility,has_super_strength,attribute_score
1,1,3-D Man,"Delroy Garrett, Jr.","Delroy Garrett, Jr.",6,"Delroy Garrett, Jr. grew up to become a track ...",17,85,30,60,...,0,0,0,0,1,0,0,0,1,345
2,2,514A (Gotham),Bruce Wayne,2-abe-sapien,10,He was one of the many prisoners of Indian Hil...,35,100,20,30,...,0,0,0,1,0,1,0,0,1,335
3,3,A.I.M. Agent,Abin Sur,3-abin-sur,7,A.I.M. agents are both soldiers and scientists...,53,90,5,20,...,0,1,0,0,0,0,0,0,0,235
4,4,A.M.A.Z.O. (CW),Abomination,4-abomination,22,The Anti Meta-human Adaptive Zootomic Organism...,"With its metallic body, it easily overpowered ...",90,100,100,...,0,1,0,0,0,0,0,0,0,590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373,1479,Zane,Zane,Zane,25,Zane was created by Dr. Julien in a small work...,"As a Nindroid, Zane has increased stamina and ...",100,35,50,...,0,1,1,1,0,1,1,1,1,445
1374,1480,Zatanna,Zatanna Zatara,Zatanna Zatara,10,Zatanna is the daughter of adventurer John Zat...,Zatanna is genetically talented with her magi...,90,10,25,...,0,0,0,0,0,0,0,0,0,310
1375,1483,Zoom,Hunter Zolomon,Hunter Zolomon,9,Hunter Zolomon had a troubled relationship wi...,"Zoom is able to alter time, to make himself ev...",75,10,100,...,0,0,0,0,1,0,0,0,0,345
1376,1484,Zoom (New 52),Hunter Zolomon,NaN,20,"Hunter Zolomon is better known as Zoom, a spee...",After tricking Barry Allen and Wally West into...,95,50,100,...,1,0,1,1,1,1,1,1,1,500
1377,1485,Zzzax,NaN,NaN,5,Zzzax was the product of an accident that occu...,NaN,45,80,75,...,0,0,0,0,1,0,0,1,1,425

In [8]:
#Merging my third dataframe with the others and creating df_total
df_total = merge.combine_first(Milestone3a)
df_total

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
0,index,name,real_name,full_name,overall_score,history_text,powers_text,intelligence_score,strength_score,speed_score,...,has_accelerated_healing,has_weapons_master,has_intelligence,has_reflexes,has_super_speed,has_durability,has_stamina,has_agility,has_super_strength,attribute_score
1,1,3-D Man,"Delroy Garrett, Jr.","Delroy Garrett, Jr.",6,"Delroy Garrett, Jr. grew up to become a track ...",17,85,30,60,...,0,0,0,0,1,0,0,0,1,345
2,2,514A (Gotham),Bruce Wayne,2-abe-sapien,10,He was one of the many prisoners of Indian Hil...,35,100,20,30,...,0,0,0,1,0,1,0,0,1,335
3,3,A.I.M. Agent,Abin Sur,3-abin-sur,7,A.I.M. agents are both soldiers and scientists...,53,90,5,20,...,0,1,0,0,0,0,0,0,0,235
4,4,A.M.A.Z.O. (CW),Abomination,4-abomination,22,The Anti Meta-human Adaptive Zootomic Organism...,"With its metallic body, it easily overpowered ...",90,100,100,...,0,1,0,0,0,0,0,0,0,590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373,1479,Zane,Zane,Zane,25,Zane was created by Dr. Julien in a small work...,"As a Nindroid, Zane has increased stamina and ...",100,35,50,...,0,1,1,1,0,1,1,1,1,445
1374,1480,Zatanna,Zatanna Zatara,Zatanna Zatara,10,Zatanna is the daughter of adventurer John Zat...,Zatanna is genetically talented with her magi...,90,10,25,...,0,0,0,0,0,0,0,0,0,310
1375,1483,Zoom,Hunter Zolomon,Hunter Zolomon,9,Hunter Zolomon had a troubled relationship wi...,"Zoom is able to alter time, to make himself ev...",75,10,100,...,0,0,0,0,1,0,0,0,0,345
1376,1484,Zoom (New 52),Hunter Zolomon,NaN,20,"Hunter Zolomon is better known as Zoom, a spee...",After tricking Barry Allen and Wally West into...,95,50,100,...,1,0,1,1,1,1,1,1,1,500
1377,1485,Zzzax,NaN,NaN,5,Zzzax was the product of an accident that occu...,NaN,45,80,75,...,0,0,0,0,1,0,0,1,1,425

In [9]:
conn = sqlite3.connect("Superhero.db")

In [10]:
df_total.tosql('table', connection, if_exists='replace', index=False)

AttributeError: 'DataFrame' object has no attribute 'tosql'

In [ ]:
cur=conn.cursor()

In [ ]:
cur.execute('SELECT * from df_total')

In [ ]:
for row in cur.execute('SELECT * FROM df_total'):
    print(row)

In [ ]:
#Created a dataframe out of my sqlite table
Superhero_db = pd.read_sql_query("SELECT * FROM df_total", conn)
Superhero_db